name: Cloudflare DNS Update

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 00:00 执行，可按需修改
  workflow_dispatch:      # 支持手动触发

jobs:
  update-dns:
    runs-on: ubuntu-latest

    steps:
      # 1. 拉取仓库
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. 设置 Python 环境
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # 3. 安装依赖
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      # 4. 执行 Cloudflare 更新脚本并推送结果到 Telegram
      - name: Run Cloudflare DNS Update
        env:
          CF_TOKENS: ${{ secrets.CF_TOKENS }}  # Cloudflare API Token
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}  # Telegram Bot Token
          CHAT_ID: ${{ secrets.CHAT_ID }}      # Telegram Chat ID
        run: |
          python cloudflare_update.py
