name: Cloudflare ProxyIP 同步

# 触发方式：手动和定时
on:
  workflow_dispatch: # 手动触发
  schedule:
    - cron: "0 */6 * * *" # 每 6 小时一次

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ 检出仓库
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2️⃣ 设置 Python 环境
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      # 3️⃣ 安装依赖
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      # 4️⃣ 配置环境变量
      - name: Set Environment Variables
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CF_ZONE_ID: ${{ secrets.CF_ZONE_ID }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: |
          echo "环境变量已加载"

      # 5️⃣ 运行同步脚本
      - name: Run Cloudflare Sync
        run: python your_script_name.py
