name: Filter & Cloudflare ProxyIP 同步

on:
  workflow_dispatch:  # 手动触发
  schedule:
    - cron: "0 6 * * *"      # 每天上午 6 点
    - cron: "0 */6 * * *"    # 每 6 小时一次

jobs:
  filter_and_sync:
    runs-on: ubuntu-latest

    env:
      MAX_PER_COUNTRY: 10  # 每个国家最多保留条数，可手动修改

    steps:
      # ---------------------------
      # 1️⃣ 检出仓库（当前仓库）
      # ---------------------------
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true  # 允许 workflow 提交回当前仓库

      # ---------------------------
      # 2️⃣ 设置 Python 环境
      # ---------------------------
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      # ---------------------------
      # 3️⃣ 安装依赖
      # ---------------------------
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      # ---------------------------
      # 4️⃣ 运行 filter_443.py
      # ---------------------------
      - name: Run filter_443.py
        run: python filter_443.py

      # ---------------------------
      # 5️⃣ 提交过滤后的文件到仓库
      # ---------------------------
      - name: Commit filtered file
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add proxyip_443_sorted.txt
          git commit -m "更新过滤后的 443 个代理 [skip ci]" || echo "No changes to commit"
          
          # 设置正确的远程仓库地址为你自己的仓库
          git remote set-url origin https://github.com/${{ github.repository }}.git

          git push origin HEAD

      # ---------------------------
      # 6️⃣ 设置 Cloudflare 环境变量
      # ---------------------------
      - name: Set Cloudflare environment variables
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CF_ZONE_ID: ${{ secrets.CF_ZONE_ID }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: echo "环境变量已加载"

      # ---------------------------
      # 7️⃣ 运行 Cloudflare 同步脚本
      # ---------------------------
      - name: Run Cloudflare Sync
        run: python sync_proxy.py

      # ---------------------------
      # 8️⃣ 提交 Cloudflare 日志文件到仓库
      # ---------------------------
      - name: Commit Cloudflare logs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add PROXYIP_*.txt
          git commit -m "更新 Cloudflare 同步日志 [skip ci]" || echo "No new logs to commit"
          
          # 设置正确的远程仓库地址为你自己的仓库
          git remote set-url origin https://github.com/${{ github.repository }}.git

          git push origin HEAD
